# Generated by Django 2.2.3 on 2019-07-12 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forma_obratnoj_svyazi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_bd',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
