# Generated by Django 2.2.3 on 2019-07-12 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forma_obratnoj_svyazi', '0002_contact_bd_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_bd',
            name='text',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
