# Generated by Django 2.2.3 on 2019-07-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forma_obratnoj_svyazi', '0003_auto_20190712_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_bd',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contact_bd',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contact_bd',
            name='phone',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
