# Generated by Django 2.2.3 on 2019-07-18 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forma_obratnoj_svyazi', '0004_auto_20190712_0648'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact_bd',
            options={'verbose_name': 'Таблица со списком обратной формы', 'verbose_name_plural': 'Таблица со списком запросов из  обратной формы'},
        ),
    ]
