# Generated by Django 2.2.3 on 2019-07-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forma_obratnoj_svyazi', '0005_auto_20190718_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_bd',
            name='select_list',
            field=models.CharField(max_length=200, null=True, verbose_name='Список в корзине'),
        ),
        migrations.AlterField(
            model_name='contact_bd',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='contact_bd',
            name='name',
            field=models.CharField(max_length=20, null=True, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='contact_bd',
            name='phone',
            field=models.CharField(max_length=11, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='contact_bd',
            name='text',
            field=models.TextField(blank=True, max_length=200, verbose_name='текст'),
        ),
    ]
