# Generated by Django 2.2.2 on 2019-07-22 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forma_obratnoj_svyazi', '0006_auto_20190720_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_bd',
            name='select_list',
            field=models.TextField(null=True, verbose_name='Список в корзине'),
        ),
    ]
