# Generated by Django 2.2.2 on 2019-07-04 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='image_title',
            field=models.ImageField(default=1, upload_to='blog/image/title'),
            preserve_default=False,
        ),
    ]
