# Generated by Django 2.2.2 on 2019-07-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190704_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='introduese',
            field=models.TextField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
