# Generated by Django 2.2.3 on 2019-07-18 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190718_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.categor_post'),
            preserve_default=False,
        ),
    ]
