# Generated by Django 2.2.3 on 2019-07-18 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_categor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date'], 'verbose_name': 'Список постов', 'verbose_name_plural': 'Cписок постов'},
        ),
    ]
