# Generated by Django 2.2.3 on 2019-07-19 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190718_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор поста'),
        ),
        migrations.AlterField(
            model_name='post',
            name='categor',
            field=models.CharField(choices=[('dfs', 'Мужской'), ('l', 'лоли')], default='dfs', max_length=1, verbose_name='Котегория поста'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=markdownx.models.MarkdownxField(max_length=1200, verbose_name='Главный текст'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_title',
            field=models.ImageField(upload_to='news/post/image/title', verbose_name='Изображения в шапки поста'),
        ),
        migrations.AlterField(
            model_name='post',
            name='introduese',
            field=models.TextField(max_length=300, verbose_name='Анотация'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок поста'),
        ),
        migrations.DeleteModel(
            name='categor_post',
        ),
    ]
