# Generated by Django 2.2.3 on 2019-07-18 11:57

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoy',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='pattern_for',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField()),
                ('text', markdownx.models.MarkdownxField(max_length=1200)),
                ('image', models.ImageField(blank=True, upload_to='prod/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('categoy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pattern_for.categoy')),
            ],
            options={
                'verbose_name': 'Запис в категориях',
                'verbose_name_plural': 'Записи в категориях',
            },
        ),
    ]
