# Generated by Django 2.2.3 on 2019-07-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pattern_for', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoy',
            options={'ordering': ['name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='categoy',
            name='name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='categoy',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
