# Generated by Django 2.2.3 on 2019-07-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pattern_for', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='categori_cat',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
