# Generated by Django 2.2.3 on 2019-07-15 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pattern_for', '0002_categori_cat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='categori_cat',
        ),
    ]
