# Generated by Django 2.2.2 on 2019-07-22 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pattern_for', '0002_auto_20190718_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pattern_for',
            name='categoy',
            field=models.CharField(choices=[('for_biz', 'для бизнеса'), ('for_gos', 'для государства'), ('for_you', 'для каждого')], default=('for_biz', 'для бизнеса'), max_length=30),
        ),
        migrations.DeleteModel(
            name='categoy',
        ),
    ]
