# Generated by Django 2.2.2 on 2019-07-22 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pattern_for', '0003_auto_20190722_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pattern_for',
            name='categoy',
            field=models.CharField(choices=[('for_biznes', 'для бизнеса'), ('for_gos', 'для государства'), ('for_you', 'для каждого')], default=('for_biznes', 'для бизнеса'), max_length=30),
        ),
    ]
