# Generated by Django 2.2.2 on 2019-07-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pattern_for', '0005_auto_20190722_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pattern_for',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/prod/'),
        ),
    ]
