# Generated by Django 2.2.2 on 2019-07-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pattern_for', '0006_auto_20190723_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pattern_for',
            name='image',
            field=models.ImageField(blank=True, upload_to='pattern'),
        ),
    ]
