# Generated by Django 2.2.2 on 2019-07-03 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='for_company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='item_block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item1', models.CharField(max_length=40)),
                ('item2', models.CharField(max_length=40)),
                ('item3', models.CharField(max_length=40)),
                ('item4', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='list_meny',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('image', models.CharField(max_length=40)),
                ('url', models.SlugField()),
            ],
        ),
    ]
