# Generated by Django 2.2.2 on 2019-07-03 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_company', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='for_company',
            new_name='about_company',
        ),
        migrations.RenameModel(
            old_name='list_meny',
            new_name='list_menu',
        ),
    ]
