# Generated by Django 2.2.2 on 2019-07-03 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_company', '0002_auto_20190703_0602'),
    ]

    operations = [
        migrations.CreateModel(
            name='car_news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
