# Generated by Django 2.2.2 on 2019-07-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_company', '0003_car_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_news',
            name='upload',
            field=models.FileField(default=1, upload_to='about_company/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='list_menu',
            name='image',
            field=models.ImageField(max_length=40, upload_to=''),
        ),
    ]
