# Generated by Django 2.2.3 on 2019-07-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_company', '0004_auto_20190703_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_menu',
            name='image',
            field=models.ImageField(max_length=40, upload_to='about_company/'),
        ),
    ]
