# Generated by Django 2.2.3 on 2019-07-18 12:21

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('about_company', '0006_auto_20190718_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_menu',
            name='content',
            field=markdownx.models.MarkdownxField(blank=True, max_length=1200),
        ),
        migrations.AlterField(
            model_name='list_menu',
            name='image',
            field=models.ImageField(blank=True, max_length=40, upload_to='about_company/other_page/'),
        ),
    ]
