# Generated by Django 2.2.3 on 2019-07-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_company', '0007_auto_20190718_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list_menu',
            old_name='url',
            new_name='slug',
        ),
        migrations.AlterField(
            model_name='list_menu',
            name='image',
            field=models.CharField(blank=True, choices=[('Novosti.pngabout_company/list_others_pages', 'Novosti.png'), ('Vakansii_80.pngabout_company/list_others_pages', 'Vakansii_80.png'), ('Informaczionnye-materialy_80.pngabout_company/list_others_pages', 'Informaczionnye-materialy_80.png'), ('Adresa_80.pngabout_company/list_others_pages', 'Adresa_80.png'), ('Sotrudnichestvo.pngabout_company/list_others_pages', 'Sotrudnichestvo.png'), ('Firminnyj-stil_80.pngabout_company/list_others_pages', 'Firminnyj-stil_80.png'), ('Telefonnyj-spravochnik_80.pngabout_company/list_others_pages', 'Telefonnyj-spravochnik_80.png'), ('Istoriya_kompanii.pngabout_company/list_others_pages', 'Istoriya_kompanii.png'), ('Licenzii.pngabout_company/list_others_pages', 'Licenzii.png'), ('Missiya_i_celi.pngabout_company/list_others_pages', 'Missiya_i_celi.png'), ('Proekty.pngabout_company/list_others_pages', 'Proekty.png'), ('Rekvizity_80.pngabout_company/list_others_pages', 'Rekvizity_80.png'), ('Antikorrupcziya_80.pngabout_company/list_others_pages', 'Antikorrupcziya_80.png'), ('Vakansii.pngabout_company/list_others_pages', 'Vakansii.png'), ('Struktura.pngabout_company/list_others_pages', 'Struktura.png'), ('Dlya-SMI_80.pngabout_company/list_others_pages', 'Dlya-SMI_80.png'), ('def', 'noimage.png'), ('Informacionnye_materialy.pngabout_company/list_others_pages', 'Informacionnye_materialy.png'), ('Kontakty.pngabout_company/list_others_pages', 'Kontakty.png'), ('image_error_full.pngabout_company/list_others_pages', 'image_error_full.png')], default=('Novosti.pngabout_company/list_others_pages', 'Novosti.png'), max_length=80),
        ),
    ]
