# Generated by Django 2.2.3 on 2019-07-20 11:27

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('about_company', '0008_auto_20190720_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_menu',
            name='content',
            field=markdownx.models.MarkdownxField(blank=True, max_length=1200, verbose_name='текст'),
        ),
        migrations.AlterField(
            model_name='list_menu',
            name='image',
            field=models.CharField(blank=True, choices=[('Licenzii.pngabout_company/list_others_pages', 'Licenzii.png'), ('Informaczionnye-materialy_80.pngabout_company/list_others_pages', 'Informaczionnye-materialy_80.png'), ('Missiya_i_celi.pngabout_company/list_others_pages', 'Missiya_i_celi.png'), ('Rekvizity_80.pngabout_company/list_others_pages', 'Rekvizity_80.png'), ('Struktura.pngabout_company/list_others_pages', 'Struktura.png'), ('Dlya-SMI_80.pngabout_company/list_others_pages', 'Dlya-SMI_80.png'), ('Istoriya_kompanii.pngabout_company/list_others_pages', 'Istoriya_kompanii.png'), ('Novosti.pngabout_company/list_others_pages', 'Novosti.png'), ('def', 'noimage.png'), ('Vakansii.pngabout_company/list_others_pages', 'Vakansii.png'), ('Adresa_80.pngabout_company/list_others_pages', 'Adresa_80.png'), ('Firminnyj-stil_80.pngabout_company/list_others_pages', 'Firminnyj-stil_80.png'), ('Informacionnye_materialy.pngabout_company/list_others_pages', 'Informacionnye_materialy.png'), ('Telefonnyj-spravochnik_80.pngabout_company/list_others_pages', 'Telefonnyj-spravochnik_80.png'), ('Kontakty.pngabout_company/list_others_pages', 'Kontakty.png'), ('Proekty.pngabout_company/list_others_pages', 'Proekty.png'), ('Antikorrupcziya_80.pngabout_company/list_others_pages', 'Antikorrupcziya_80.png'), ('image_error_full.pngabout_company/list_others_pages', 'image_error_full.png'), ('Vakansii_80.pngabout_company/list_others_pages', 'Vakansii_80.png'), ('Sotrudnichestvo.pngabout_company/list_others_pages', 'Sotrudnichestvo.png')], default=('Licenzii.pngabout_company/list_others_pages', 'Licenzii.png'), max_length=80, verbose_name='изображения'),
        ),
        migrations.AlterField(
            model_name='list_menu',
            name='slug',
            field=models.SlugField(verbose_name='уникальная ссылка'),
        ),
        migrations.AlterField(
            model_name='list_menu',
            name='title',
            field=models.CharField(max_length=40, verbose_name='Заголовок'),
        ),
    ]
