# Generated by Django 2.2.2 on 2019-07-22 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_company', '0009_auto_20190720_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_menu',
            name='image',
            field=models.CharField(blank=True, choices=[('Sotrudnichestvo.pngabout_company/list_others_pages', 'Sotrudnichestvo.png'), ('Istoriya_kompanii.pngabout_company/list_others_pages', 'Istoriya_kompanii.png'), ('Adresa_80.pngabout_company/list_others_pages', 'Adresa_80.png'), ('def', 'noimage.png'), ('Vakansii.pngabout_company/list_others_pages', 'Vakansii.png'), ('Proekty.pngabout_company/list_others_pages', 'Proekty.png'), ('Licenzii.pngabout_company/list_others_pages', 'Licenzii.png'), ('Kontakty.pngabout_company/list_others_pages', 'Kontakty.png'), ('Antikorrupcziya_80.pngabout_company/list_others_pages', 'Antikorrupcziya_80.png'), ('Firminnyj-stil_80.pngabout_company/list_others_pages', 'Firminnyj-stil_80.png'), ('image_error_full.pngabout_company/list_others_pages', 'image_error_full.png'), ('Informaczionnye-materialy_80.pngabout_company/list_others_pages', 'Informaczionnye-materialy_80.png'), ('Rekvizity_80.pngabout_company/list_others_pages', 'Rekvizity_80.png'), ('Dlya-SMI_80.pngabout_company/list_others_pages', 'Dlya-SMI_80.png'), ('Missiya_i_celi.pngabout_company/list_others_pages', 'Missiya_i_celi.png'), ('Vakansii_80.pngabout_company/list_others_pages', 'Vakansii_80.png'), ('Struktura.pngabout_company/list_others_pages', 'Struktura.png'), ('Informacionnye_materialy.pngabout_company/list_others_pages', 'Informacionnye_materialy.png'), ('Telefonnyj-spravochnik_80.pngabout_company/list_others_pages', 'Telefonnyj-spravochnik_80.png'), ('Novosti.pngabout_company/list_others_pages', 'Novosti.png')], default=('Sotrudnichestvo.pngabout_company/list_others_pages', 'Sotrudnichestvo.png'), max_length=80, verbose_name='изображения'),
        ),
    ]
