# Generated by Django 2.2.2 on 2019-07-15 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_category', '0002_name_cat_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items_cat',
            name='slug',
        ),
    ]
