# Generated by Django 2.2.2 on 2019-07-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_category', '0003_remove_items_cat_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items_cat',
            name='id',
        ),
        migrations.AlterField(
            model_name='items_cat',
            name='name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
