# Generated by Django 2.2.2 on 2019-07-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_category', '0004_auto_20190715_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='items_cat',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
